name: myapp

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - "gunicorn"
      - "training_django_project.wsgi:application"
      - "--bind"
      - "0.0.0.0:8000"
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./training_django_project/database:/app/database
