# Generated by Django 6.0.4 on 2026-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0006_order_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("name", "price")},
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
