# Generated by Django 6.0.4 on 2026-04-23 13:42

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0008_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.product_preview_directory_path,
            ),
        ),
    ]
