# Generated by Django 6.0.4 on 2026-04-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0010_order_receipt_productimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name", "price"),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
