# Generated by Django 6.0.4 on 2026-04-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0011_alter_product_options_order_receipt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(null=True, upload_to="orders/receipts/"),
        ),
    ]
